version: '3'

services:
  front-app:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src:ro
    env_file:
      - ./front/.env