FROM node:lts

WORKDIR /app

COPY front/package.json .

COPY front/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN npm install

COPY ./front .

EXPOSE 3000

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "npm", "run", "dev" ]