version: '3'

services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - ./src:/app/src:ro
    # env_file:
    #   - ./.env