FROM node:lts

WORKDIR /app

COPY front/package.json .

COPY front/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN npm install

COPY ./front .

ENTRYPOINT [ "/entrypoint.sh" ]

RUN npm run build